import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

import Footer from '../components/Footer';
import Navbar from '../components/Navbar';
import HeroSection from '../components/sections/HeroSection';
import MainSection from '../components/sections/MainSection';

import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>PG</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Navbar />
			<main>
				<HeroSection />

				<MainSection />
			</main>
			<Footer />
		</div>
	);
};

export default Home;
